from collections.abc import Iterable
from typing import Protocol

from infrastructure.models.todo import Todo


class ITodoRepository(Protocol):
    def list_todos(self) -> list[Todo]: ...
    def create_todo(self, title: str) -> None: ...
    def get_todo(self, todo_id: int) -> Todo | None: ...
    def update_todo(self, todo_id: int, title: str) -> bool: ...
    def toggle_todo(self, todo_id: int) -> None: ...
    def delete_todo(self, todo_id: int) -> bool: ...
    def delete_completed_todos(self, todos: Iterable[Todo]) -> None: ...
