from collections.abc import Iterable
from typing import Protocol

from models.todo import Todo


class IJobRepository(Protocol):
    def list_jobs(self) -> list[Todo]: ...
    def create_job(self, title: str) -> None: ...
    def get_job(self, job_id: int) -> Todo | None: ...
    def update_job(self, job_id: int, title: str) -> bool: ...
    def toggle_job(self, job_id: int) -> None: ...
    def delete_job(self, job_id: int) -> bool: ...
    def delete_completed(self, jobs: Iterable[Todo]) -> None: ...
