from typing import Protocol

from core.monitoring.models import QueueJob, QueueStats


class IQueueMonitoringRepository(Protocol):
    def get_queue_stats(self) -> QueueStats: ...
    def list_queue_jobs(self, limit: int = 50, offset: int = 0, status_filter: str | None = None) -> list[QueueJob]: ...
    def count_queue_jobs(self, status_filter: str | None = None) -> int: ...
