from typing import Protocol

from infrastructure.models.product import Product


class IProductRepository(Protocol):
    def list_products(self, limit: int = 100, offset: int = 0, crawl_status: str | None = None) -> list[Product]: ...

    def count_products(self, crawl_status: str | None = None) -> int: ...

    def create_pending_product(self, remote_url: str) -> Product: ...

    def delete_product(self, product_id: int) -> bool: ...
