from .field_names import CDP_CONNECTION_FIELD_NAMES, PRODUCT_FIELD_NAMES, TODO_FIELD_NAMES
from .table_names import CDP_CONNECTION_TABLE_NAME, PRODUCT_TABLE_NAME, TODO_TABLE_NAME

__all__ = [
    "CDP_CONNECTION_FIELD_NAMES",
    "CDP_CONNECTION_TABLE_NAME",
    "PRODUCT_FIELD_NAMES",
    "PRODUCT_TABLE_NAME",
    "TODO_FIELD_NAMES",
    "TODO_TABLE_NAME",
]
