from typing import Final

TODO_FIELD_NAMES: Final[tuple[str, ...]] = ("id", "title", "is_done", "created_at", "updated_at")
CDP_CONNECTION_FIELD_NAMES: Final[tuple[str, ...]] = (
    "id",
    "name",
    "host",
    "port",
    "browser",
    "ws_path",
    "username",
    "password",
    "is_active",
    "notes",
    "created_at",
    "updated_at",
)
PRODUCT_FIELD_NAMES: Final[tuple[str, ...]] = (
    "id",
    "thumbnail",
    "name",
    "category",
    "price",
    "images_url",
    "barcode",
    "code",
    "remote_id",
    "remote_url",
    "description",
    "crawl_status",
    "crawl_at",
    "created_at",
    "updated_at",
)
CATEGORY_CRAWL_JOB_FIELD_NAMES: Final[tuple[str, ...]] = (
    "id",
    "site_key",
    "category_name",
    "category_url",
    "normalized_category_url",
    "crawl_status",
    "total_products",
    "products_per_page",
    "total_pages",
    "enqueued_products_count",
    "crawl_at",
    "error_message",
    "created_at",
    "updated_at",
)

MANAGED_BROWSER_FIELD_NAMES: Final[tuple[str, ...]] = (
    "id",
    "name",
    "browser_type",
    "host",
    "port",
    "executable_path",
    "user_data_dir",
    "headless",
    "launch_args",
    "is_active",
    "status",
    "pid",
    "last_started_at",
    "last_seen_at",
    "notes",
    "error_message",
    "created_at",
    "updated_at",
)
